# Generated by Django 5.0.6 on 2024-06-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_ph_no'),
        ('post', '0003_alter_post_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='author',
        ),
    ]
