# Generated by Django 5.0.6 on 2024-06-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_category_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_model',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
